component: apicontrolplane-service

build:
  project_file: src/Roblox.ApiControlPlane.Service.csproj
  component_directory: ./.deploy

  additional_args:
    - -p:DockerTag=${{ env.NOMAD_VERSION }}

  docker:
    docker_file: Dockerfile
    image_name: docker.artifactory.rbx.com/micro-services-platform/apicontrolplane-service
    
deployment:
  count: 2
  namespace: micro-services

  job: ${{ env.NOMAD_ENVIRONMENT }}-roblox-apicontrolplane-service

  vault_role: rbx-platform-token-reader

  # Passed to the meta section in Nomad
  meta:
    ENVIRONMENT: ${{ env.NOMAD_ENVIRONMENT }}

  containers: # Maps to the groups section in Nomad
    - image: docker.artifactory.rbx.com/micro-services-platform/apicontrolplane-service
      resources:
        cpu: ${{ env.NOMAD_CPU }}
        ram: ${{ env.NOMAD_RAM }}
      network:
        ports:
          http: 
            to: 5000
      services:
        - name: ${{ env.NOMAD_ENVIRONMENT }}-roblox-apicontrolplane-service
          port: http
          tags:
            - ${{ env.NOMAD_ENVIRONMENT }}
            - prometheus
            - Roblox.ApiControlPlane.Service
            - ApiControlPlane

            # Traffic: Private | Roblox.ApiControlPlane.Service
            - haproxy.enable=true
            - haproxy.protocol=http
            - haproxy.fe.fqdn=apicontrolplane.api.rbxlabs.net
            - haproxy.fe.entrypoints=http,https
          checks:
            - type: http
              path: /health

      config_maps:
        - destination: secrets/file.env
          env: true
          on_change: restart
          data: |
            DEFAULT_LOG_LEVEL=Information
            ASPNETCORE_URLS="http://+:5000"
            
            AppName=Roblox.ApiControlPlane.ApiControlPlaneService
            
            VAULT_ADDR="https://cou1-vault.simulprod.com"
            VAULT_TOKEN="{{ with secret "secret/teams/applications/vault-providers" }}{{ .Data.vault_token }}{{ end }}"